//! On-disk run records: `<data_dir>/runs/<run-id>/{run.json, events.jsonl}` (atomic writes).

use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use ct_agentd::{AgentEvent, BackendKind, ModelSel};
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::{RunInfo, RunSpec, RunState};

const MAX_EVENT_LOG: u64 = 8 << 20;

#[derive(Serialize, Deserialize, Clone, Debug)]
pub(crate) struct Stored {
    pub id: String,
    pub repo: PathBuf,
    pub prompt: String,
    pub backend: String,
    pub provider: Option<String>,
    pub model_id: String,
    pub thinking: Option<String>,
    pub base_ref: String,
    pub isolate: bool,
    pub base_sha: String,
    pub branch: Option<String>,
    pub worktree: Option<PathBuf>,
    /// queued | running | succeeded | failed | aborted | interrupted
    pub state: String,
    pub state_msg: Option<String>,
    pub submitted_ms: i64,
    pub started_ms: i64,
    pub ended_ms: Option<i64>,
    pub files_changed: u32,
    pub pid: Option<u32>,
    pub pid_start: Option<u64>,
    pub head_sha: Option<String>,
}

fn backend_str(b: BackendKind) -> &'static str {
    match b {
        BackendKind::Pi => "pi",
        BackendKind::Claude => "claude",
        BackendKind::Codex => "codex",
    }
}

fn backend_parse(s: &str) -> Result<BackendKind> {
    Ok(match s {
        "pi" => BackendKind::Pi,
        "claude" => BackendKind::Claude,
        "codex" => BackendKind::Codex,
        o => return Err(anyhow!("unknown backend {o:?}")),
    })
}

impl Stored {
    pub fn new(id: String, spec: &RunSpec, base_sha: String, now: i64) -> Stored {
        Stored {
            id,
            repo: spec.repo.clone(),
            prompt: spec.prompt.clone(),
            backend: backend_str(spec.model.backend).into(),
            provider: spec.model.provider.clone(),
            model_id: spec.model.id.clone(),
            thinking: spec.model.thinking.clone(),
            base_ref: spec.base_ref.clone(),
            isolate: spec.isolate,
            base_sha,
            branch: None,
            worktree: None,
            state: "queued".into(),
            state_msg: None,
            submitted_ms: now,
            started_ms: 0,
            ended_ms: None,
            files_changed: 0,
            pid: None,
            pid_start: None,
            head_sha: None,
        }
    }

    pub fn backend(&self) -> Result<BackendKind> {
        backend_parse(&self.backend)
    }

    pub fn model(&self) -> Result<ModelSel> {
        Ok(ModelSel {
            backend: self.backend()?,
            provider: self.provider.clone(),
            id: self.model_id.clone(),
            thinking: self.thinking.clone(),
        })
    }

    pub fn run_state(&self) -> RunState {
        let msg = || self.state_msg.clone().unwrap_or_default();
        match self.state.as_str() {
            "queued" => RunState::Queued,
            "running" => RunState::Running,
            "succeeded" => RunState::Succeeded,
            "failed" => RunState::Failed(msg()),
            "aborted" => RunState::Aborted,
            _ => RunState::Interrupted,
        }
    }

    pub fn set_state(&mut self, s: &RunState) {
        let (k, m) = match s {
            RunState::Queued => ("queued", None),
            RunState::Running => ("running", None),
            RunState::Succeeded => ("succeeded", None),
            RunState::Failed(m) => ("failed", Some(m.clone())),
            RunState::Aborted => ("aborted", None),
            RunState::Interrupted => ("interrupted", None),
        };
        self.state = k.into();
        self.state_msg = m;
    }

    pub fn is_active(&self) -> bool {
        matches!(self.state.as_str(), "queued" | "running")
    }

    pub fn info(&self) -> RunInfo {
        RunInfo {
            id: self.id.clone(),
            spec: RunSpec {
                repo: self.repo.clone(),
                prompt: self.prompt.clone(),
                model: self.model().unwrap_or(ModelSel {
                    backend: BackendKind::Pi,
                    provider: self.provider.clone(),
                    id: self.model_id.clone(),
                    thinking: self.thinking.clone(),
                }),
                base_ref: self.base_ref.clone(),
                isolate: self.isolate,
            },
            base_sha: self.base_sha.clone(),
            branch: self.branch.clone(),
            worktree: self.worktree.clone(),
            state: self.run_state(),
            started_ms: self.started_ms,
            ended_ms: self.ended_ms,
            files_changed: self.files_changed,
        }
    }
}

/// Ids are generated by us (`<hex>-<8 hex>`); anything else is never joined onto a path.
pub fn valid_id(id: &str) -> bool {
    let mut p = id.split('-');
    let (Some(a), Some(b), None) = (p.next(), p.next(), p.next()) else { return false };
    !a.is_empty() && a.len() <= 16 && b.len() == 8 && id.bytes().all(|c| c.is_ascii_hexdigit() || c == b'-')
}

pub fn runs_dir(data: &Path) -> PathBuf {
    data.join("runs")
}

pub fn run_dir(data: &Path, id: &str) -> PathBuf {
    runs_dir(data).join(id)
}

pub fn save(data: &Path, s: &Stored) -> Result<()> {
    if !valid_id(&s.id) {
        return Err(anyhow!("invalid run id {:?}", s.id));
    }
    let dir = run_dir(data, &s.id);
    fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    let tmp = dir.join("run.json.tmp");
    let body = serde_json::to_vec_pretty(s)?;
    {
        let mut f = File::create(&tmp)?;
        f.write_all(&body)?;
        f.sync_all()?;
    }
    fs::rename(&tmp, dir.join("run.json"))?;
    Ok(())
}

/// All readable run records, oldest submission first. Corrupt records are skipped.
pub fn load_all(data: &Path) -> Vec<Stored> {
    let mut v: Vec<Stored> = Vec::new();
    let Ok(rd) = fs::read_dir(runs_dir(data)) else { return v };
    for e in rd.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        if !valid_id(&name) {
            continue;
        }
        let Ok(b) = fs::read(e.path().join("run.json")) else { continue };
        if let Ok(s) = serde_json::from_slice::<Stored>(&b) {
            if s.id == name {
                v.push(s);
            }
        }
    }
    v.sort_by(|a, b| (a.submitted_ms, &a.id).cmp(&(b.submitted_ms, &b.id)));
    v
}

pub struct EventLog {
    f: Option<File>,
    bytes: u64,
}

impl EventLog {
    pub fn open(data: &Path, id: &str) -> EventLog {
        let f = OpenOptions::new().create(true).append(true).open(run_dir(data, id).join("events.jsonl")).ok();
        let bytes = f.as_ref().and_then(|f| f.metadata().ok()).map(|m| m.len()).unwrap_or(0);
        EventLog { f, bytes }
    }

    pub fn path(data: &Path, id: &str) -> PathBuf {
        run_dir(data, id).join("events.jsonl")
    }

    pub fn append(&mut self, ev: &AgentEvent) {
        let Some(f) = self.f.as_mut() else { return };
        if self.bytes >= MAX_EVENT_LOG {
            return;
        }
        let ts = ct_store::now_ms();
        let v = match ev {
            AgentEvent::Started => json!({"ts":ts,"ev":"started"}),
            AgentEvent::TextDelta(t) => json!({"ts":ts,"ev":"text","text":crate::reasons::mask_secrets(t)}),
            AgentEvent::ToolStart { id, name, summary } => json!({"ts":ts,"ev":"tool_start","id":id,"name":name,"summary":crate::reasons::mask_secrets(summary)}),
            AgentEvent::ToolEnd { id, name, ok, path } => json!({"ts":ts,"ev":"tool_end","id":id,"name":name,"ok":ok,"path":path}),
            AgentEvent::Usage { input, output, cost } => json!({"ts":ts,"ev":"usage","input":input,"output":output,"cost":cost}),
            AgentEvent::Settled { ok, error } => json!({"ts":ts,"ev":"settled","ok":ok,"error":error}),
            AgentEvent::Stderr(t) => json!({"ts":ts,"ev":"stderr","text":crate::reasons::mask_secrets(t)}),
            AgentEvent::Exited(c) => json!({"ts":ts,"ev":"exited","code":c}),
        };
        let mut line = v.to_string();
        line.push('\n');
        if f.write_all(line.as_bytes()).is_ok() {
            self.bytes += line.len() as u64;
        }
        if self.bytes >= MAX_EVENT_LOG {
            let _ = f.write_all(b"{\"ev\":\"log_truncated\"}\n");
        }
    }
}
