[package]
name = "ct-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "codetrail"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
similar.workspace = true
egui.workspace = true
eframe.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
ct-core = { path = "../ct-core" }
ct-store = { path = "../ct-store" }
ct-agent = { path = "../ct-agent" }
ct-agentd = { path = "../ct-agentd" }
ct-runs = { path = "../ct-runs" }
parking_lot.workspace = true

[dev-dependencies]
tempfile.workspace = true
